### ISSUE TITLE
Map Documentation

### ISSUE THREAD

**Issue by TeGuy** [thecodingmachine/workadventure-map-starter-kit#1]
Hi, the last sentence in the README is:

```
In order to design a map that will be readable by WorkAdventure, you will have to respect some constraints.

In particular, you will need to:

- set a start position for the players
- configure the "floor layer" (so that WorkAdventure can correctly display characters above the floor, but under the ceiling)
- eventually, you can place exits that link to other maps

All this is described in the WorkAdventure documentation. Please be sure to check it out.
```
But the link leads to the github page of the workadventu.re project itself. Neither there, nor in the wiki or any doc page there is a deeper documentation.

Where may I find deeper information about what attributes are supported?

**Comment by ValdoTR** [comment]
Hi @TeGuy :)
I'm not sure which text you mean but in the README you can find a link to the tutorial for building maps : https://workadventu.re/map-building

**Comment by moufmouf** [comment]
@ValdoTR The issue is quite old and was fixed. I think I forgot to close it :D
