### ISSUE TITLE
Missing attribution of authors for tilesets

### ISSUE THREAD

**Issue by QbDesu** [thecodingmachine/workadventure-map-starter-kit#11]
This repo does not attribute the authors of it's tilemaps and therefore violates at least one of the tilesets' licenses.

https://opengameart.org/content/32x32-tilemap-grass-dungeon-floors-snow-water
This gfx0's `32x32 tilemap grass dungeon floors snow water` aka `floortileset.png` which is licensed under CC-BY 4.0. The author isn't even credited.

The other tileset `tilesets_deviant_milkian_1.png` is "created" by [Milkian](https://www.deviantart.com/milkian)
https://www.deviantart.com/milkian/art/Tilesets-FSM-RM2K3-para-VX-Ace-Set-Escritorio-651542743
Milkian is seems to be fine with not being credited judging by some of his other tilemaps but the description of that tilemaps as translated by Google Translate reads:
> These tiles do not belong to me. These are tiles originally created by First Seed Material for Rpg Maker 2003.
I made a conversion to be used in Rpg Maker VX or VX Ace.

Meaning he isn't the copyright holder anyway making the licese situation a bit more complicated.
Even if he was the copyright holder it would be a good idea to credit him anyway, simply because people using these templates can find some nice tilesets on his deviantart to work with and because is just a nice thing todo in general.

**Comment by ValdoTR** [comment]
You are right @QbDesu,
I will simply replace the current tilesets, and the one created by Milkian is not free to use anyway ^^
