### ISSUE TITLE
[WEB_GL] RENDER WARNING: texture bound to texture unit 1 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?

### ISSUE THREAD

**Issue by nathPay** [thecodingmachine/workadventure-map-starter-kit#31]
Hi,
I tried to add a new tileSet to my workAdventure map but some errors occured when tested locally.
*What I did*
- Import tileSet.png using embedded method
- Adding tiles in my map (Tiles are in 32x32) (At this point Tiled is working well)
- npm install (node 10.x throw an issue so i'm using 16.x)
- npm run start (Server start well)
- Viewing that all my change using the new tileset does not appear
- test with firefox and safari, same issue

*Browser Console*
Every time it update the map (by moving the woka) it throw this warning: 
`[.WebGL-0x142047c00]RENDER WARNING: texture bound to texture unit 1 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?`

Is like this:
![workAdventureTest](https://user-images.githubusercontent.com/45284476/151783286-d9f49706-3c0f-493a-a742-c0ca0366527f.png)

Should be like this:
<img width="290" alt="Tiled" src="https://user-images.githubusercontent.com/45284476/151783295-26968b42-5771-4797-ad6a-02bf69a7690d.png">

TileSet used:
[tileSet](https://user-images.githubusercontent.com/45284476/151783516-ee42d0e0-0060-4f28-a52f-0669d9c87d93.png)

Thanks for your help!

**Comment by ValdoTR** [comment]
Hi @nathPay 
Your tileset is WAY TO BIG. It has a height of 20kpx. I'm sure your error is simply related to the size of it.
Try using tilesets of 2048px max in width and height ;)

**Comment by nathPay** [comment]
Hi @ValdoTR ! 
Thank you for the answer ! It is working well now :)
