### ISSUE TITLE
Using Tiled v1.9: unable to setup an area

### ISSUE THREAD

**Issue by clementlize** [thecodingmachine/workadventure-map-starter-kit#39]
Hello,

I created my own map using this template and tested it locally. I faced an issue: the zones I set do not work. When stepping in a silent zone, nothing happened.

I then compared the template JSON with my edited JSON, and noticed an important difference: the zones objects are shaped differently. I suppose that this is due to changes in new Tiled versions.

This works
`{
    "type":"area",
    ...
  }`

This happens whenever I save my file using Tiled 1.9.0, and makes my zones inactive
`{
    "class":"area",
    ...
  }`

I will keep replacing class by type for my map, but I think other people might also face this issue.
Have a great day!

**Comment by kyunal** [comment]
It's not necessary to replace the JSON property every time, instead you can enable Tiled's compatibility mode for the project as explained here: https://www.mapeditor.org/2022/06/25/tiled-1-9-released.html

For the time this (breaking) change is not adopted, this workaround should probably be mentioned in the docs and README. Another option would be to supply a .tiled-project to the starter-kit, which has this option set by default.

**Comment by clementlize** [comment]
Indeed, having a project to start with would be great. I was confused at first that there was no project to open but only a JSON map.
Thank you for the compatibility tip anyway :)

**Comment by ValdoTR** [comment]
We will fix this, so like users don't have to do this, thanks!

**Comment by nolway** [comment]
@moufmouf The issue has been fixed ?
