### ISSUE TITLE
linking maps on localhost:8080

### ISSUE THREAD

**Issue by onkeloki** [thecodingmachine/workadventure-map-starter-kit#7]
i have 2 maps 
start.json and main.json

use exitScehneUrl  = main.json  (in start.json)
to link from start to main map
it works well on a real web host..  but within the workadventure-map-starter-kit and webpack .. it eats the port:8080
so it does not navigate between the maps because the 8080 get lost

**Comment by moufmouf** [comment]
Ho.... I'll definitely check that!
